[build]
  # Comando para construir la aplicaci칩n
  command = "npm run build"
  
  # Directorio donde se genera el build (Vite usa 'dist' por defecto)
  publish = "dist"
  
  # Variables de entorno para el build (si necesitas)
  # environment = { NODE_VERSION = "18" }

[build.environment]
  # Versi칩n de Node.js a usar
  NODE_VERSION = "18"

# Configuraci칩n para SPA (Single Page Application)
# Redirige todas las rutas a index.html para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad opcionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets est치ticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"