[build]
  # Comando para construir la aplicación con verificación de variables
  command = "chmod +x scripts/netlify-build.sh && scripts/netlify-build.sh"
  
  # Directorio donde se genera el build (Vite usa 'dist' por defecto)
  publish = "dist"

[build.environment]
  # Versión de Node.js a usar
  NODE_VERSION = "18"
  # Aumentar memoria para el build
  NODE_OPTIONS = "--max-old-space-size=4096"

# Configuración para SPA (Single Page Application)
# Redirige todas las rutas a index.html para React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad opcionales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"